Repository UNOA-Project/UNOA-Front, pull requests merged in 2025-06, with the labels that each got.

#2 Feat: Header 구현
  src/assets/Logo.svg
  src/components/Header.jsx
  src/routes/Layout.jsx
  src/routes/index.jsx
Labels: FEAT

#5 Feat: 리스트페이지 필터 구현
  package-lock.json
  src/components/AppSelector/AppSelector.jsx
  src/components/AppSelector/AppSelector.module.css
  src/components/FilterButton/FilterButton.jsx
  src/components/FilterButton/FilterButton.module.css
  src/components/FilterModal/FilterModal.jsx
  src/components/FilterModal/FilterModal.module.css
  src/components/FilterSort/FilterSort.jsx
  src/components/FilterSort/FilterSort.module.css
  src/components/PlanCard/PlanCard.jsx
  src/components/PlanCard/PlanCard.module.css
  src/components/PlanCardSystem/PlanCardSystem.jsx
  src/components/PlanCardSystem/PlanCardSystem.module.css
  src/components/PlanGrid/PlanGrid.jsx
  src/components/PlanGrid/PlanGrid.module.css
  src/components/TabMenu/TabMenu.jsx
  src/components/TabMenu/TabMenu.module.css
  src/data/appsData.js
  src/data/planData.js
  src/hooks/usePlanFilter.js
Labels: CHORE, STYLE, FEAT

#7 Feat: 리스트페이지 정렬 구현
  public/images/icons/add.png
  public/images/icons/call.png
  public/images/icons/down_arrow.png
  public/images/icons/filter_icon.png
  public/images/icons/message.png
  public/images/icons/proicons_arrow.png
  public/images/icons/up_arrow.png
  public/images/icons/넷플릭스.png
  public/images/icons/디즈니+티빙.png
  public/images/icons/디즈니.png
  public/images/icons/멀티팩.png
  public/images/icons/밀리의서재.png
  public/images/icons/바이브.png
  public/images/icons/삼성팩.png
  public/images/icons/신한카드Air.png
  public/images/icons/아이들나라.png
  public/images/icons/애플디바이스팩.png
  public/images/icons/액션캠.png
  public/images/icons/우리집돌봄이.png
  public/images/icons/우리집지킴이.png
  public/images/icons/유튜브.png
  public/images/icons/유플레이.png
  public/images/icons/일리커피구독.png
  public/images/icons/주유편의점.png
  public/images/icons/지니뮤직.png
  public/images/icons/티빙.png
  public/images/icons/폰교체패스.png
  public/images/icons/헬로렌탈.png
  src/components/FilterSort/FilterSort.jsx
  src/components/FilterSort/FilterSort.module.css
  src/components/PlanCard/PlanCard.jsx
  src/components/PlanCard/PlanCard.module.css
  src/components/PlanCardSystem/PlanCardSystem.jsx
  src/pages/PlanListPage.jsx
Labels: REFACTOR, CHORE, STYLE, FEAT

#14 Feat: 회원가입 페이지 구현
  package-lock.json
  package.json
  src/apis/userApi.js
  src/assets/arrow-right.svg
  src/assets/kakao-icon.svg
  src/components/FormField.jsx
  src/components/Header.jsx
  src/components/ToastSuccessRegister.jsx
  src/hooks/useToast.js
  src/index.css
  src/pages/RegisterPage.jsx
  src/routes/Layout.jsx
Labels: REFACTOR, BUILD, STYLE, FEAT

#16 Refactor: tailwind로 디자인 수정
  src/components/chatbot/ChatContainer.jsx
  src/components/chatbot/ChatHeader.jsx
  src/components/chatbot/ChatHeader.module.css
  src/components/chatbot/ChatMode.jsx
  src/pages/ChatbotPage.jsx
  src/pages/ChatbotPage.module.css
Labels: REFACTOR, STYLE

#17 Feat: 로그인 페이지 구현
  package-lock.json
  src/apis/userApi.js
  src/hooks/useToast.js
  src/pages/LoginPage.jsx
  src/routes/Layout.jsx
Labels: STYLE, FEAT

#21 feat: 챗봇 내에서 요금제 추천 카드 구현
  src/components/chatbot/MessageItem.jsx
  src/components/chatbot/MessageItem.module.css
  src/components/chatbot/PlanCard.jsx
  src/hooks/useChat.js
Labels: REFACTOR, FEAT

#22 Feat: 인증 상태 UI변경 로그아웃 기능
  src/apis/userApi.js
  src/components/Header.jsx
  src/contexts/AuthContext.jsx
  src/main.jsx
  src/pages/LoginPage.jsx
Labels: REFACTOR, FEAT

#25 Fix: conflict 해결
  src/components/Header.jsx
Labels: BUG, CHORE

#24 Feat: chatbot 간단모드 반응형
  src/components/chatbot/ChatContainer.jsx
  src/components/chatbot/ChatHeader.jsx
  src/components/chatbot/SimpleMode.jsx
  src/components/chatbot/SimpleModeForm.jsx
  src/data/questions.js
  src/index.css
  src/pages/ChatbotPage.jsx
Labels: STYLE, FEAT

#26 Feat: 카카오로그인 구현
  src/pages/LoginPage.jsx
  src/pages/RegisterPage.jsx
Labels: FEAT

#28 Feat: 채팅로그 로컬 IP 저장 및 초기화 구현
  .gitignore
  src/assets/refresh.svg
  src/components/chatbot/ChatHeader.jsx
  src/components/chatbot/ChatModeWelcome.jsx
  src/components/chatbot/MessageList.jsx
  src/components/chatbot/PlanCard.jsx
  src/hooks/useChat.js
  src/hooks/useUI.js
  src/pages/ChatbotPage.jsx
Labels: REFACTOR, FEAT

#29 Design: 요금제카드 UI 2차 수정
  public/images/icons/아이들나라 스탠다드+러닝.png
  public/images/icons/주유 편의점.png
  src/components/ListPage/PlanCard/PlanCard.jsx
  src/data/appsData.js
Labels: REFACTOR, CHORE, STYLE

#30 Feat: 입력form 에러 표시 애니메이션
  src/components/FormField.jsx
  src/components/Header.jsx
  src/pages/LoginPage.jsx
  src/pages/RegisterPage.jsx
Labels: STYLE, FEAT

#31 Fix: 간단 모드 UI 반응형 개선
  src/components/chatbot/ChatHeader.jsx
  src/components/chatbot/SimpleMode.jsx
  src/components/chatbot/SimpleModeForm.jsx
Labels: STYLE

#34 Fix: 마크다운 태그 깨짐 현상 해결
  package-lock.json
  package.json
  src/components/chatbot/MessageItem.jsx
  src/components/chatbot/MessageItem.module.css
  src/hooks/useChat.js
Labels: BUG, CHORE

#37 Design: 리스트페이지 탭, Feat: 탭 드래그 기능, Fix: 더보기버튼, 비교하기 버튼 겹침현상
  src/components/ListPage/PlanCard/PlanCard.jsx
  src/components/ListPage/PlanCard/PlanCard.module.css
  src/components/ListPage/PlanCardSystem/PlanCardSystem.jsx
  src/components/ListPage/PlanCardSystem/PlanCardSystem.module.css
  src/components/ListPage/PlanGrid/PlanGrid.module.css
  src/components/ListPage/TabMenu/TabMenu.jsx
  src/components/ListPage/TabMenu/TabMenu.module.css
  src/pages/PlanListPage.jsx
Labels: REFACTOR, CHORE, STYLE, FEAT

#43 Design: 채팅모드 수정
  src/assets/WelcomeNoa.svg
  src/components/chatbot/ChatModeWelcome.jsx
  src/components/chatbot/SimpleModeWelcome.jsx
  src/index.css
Labels: STYLE

#49 Feat: 마이페이지 혜택
  public/images/benefits/cgv.png
  public/images/benefits/gs the fresh.png
  public/images/benefits/gs25.png
  public/images/benefits/vips.png
  public/images/benefits/ybm net.png
  public/images/benefits/굽네치킨.png
  public/images/benefits/데이터 쿠폰.png
  public/images/benefits/도미노피자.png
  public/images/benefits/동아제약 디몰.png
  public/images/benefits/뚜레쥬르.png
  public/images/benefits/롯데시네마.png
  public/images/benefits/메가박스.png
  public/images/benefits/미스터피자.png
  public/images/benefits/반올림피자.png
  public/images/benefits/배스킨라빈스.png
  public/images/benefits/원스토어.png
  public/images/benefits/카모아.png
  public/images/benefits/코엑스아쿠아리움.png
  public/images/benefits/파리바게트.png
  public/images/benefits/파파존스.png
  public/images/benefits/피싱 해킹 안심 서비스.png
  public/images/benefits/피자헛.png
  public/rateIcon/10년 이상.svg
  public/rateIcon/2년 이상.svg
  public/rateIcon/5년 이상.svg
  src/apis/userApi.js
  src/assets/x-icon.svg
  src/components/Benefits/GradeCard.jsx
  src/components/Benefits/UserBenefitsSection.jsx
  src/components/Modal/GradeGuideModal.jsx
  src/components/Modal/Modal.jsx
  src/index.css
  src/pages/MyPage.jsx
Labels: BUILD, STYLE, FEAT

#50 Fix: 마크다운 오류 최종 수정
  src/hooks/useChat.js
Labels: BUG

#51 Refactor: 마이페이지 혜택
  src/apis/userApi.js
  src/components/Modal/GradeGuideModal.jsx
  src/components/MyPage/GradeCard.jsx
  src/components/MyPage/UserBenefits.jsx
  src/components/MyPage/UserPlan.jsx
  src/components/chatbot/SimpleMode.jsx
  src/pages/MyPage.jsx
Labels: REFACTOR

#52 Chore: 전체 디테일 수정
  index.html
  public/favicon.svg
  src/hooks/usePlanFilter.js
  src/hooks/useSocket.js
Labels: CHORE, FEAT

#57 Design: 로딩스피너, 실패UI스타일수정
  src/components/ListPage/PlanCardSystem/PlanCardSystem.module.css
  src/components/chatbot/LoadingScreen.jsx
Labels: STYLE

#62 Refactor: 전체 파일 디테일 수정
  public/images/icons/filter_icon.png
  public/images/icons/filter_icon.svg
  src/assets/section/mouse.png
  src/components/Footer.jsx
  src/components/ListPage/AppSelector/AppSelector.jsx
  src/components/ListPage/FilterButton/FilterButton.jsx
  src/components/ListPage/FilterModal/FilterModal.jsx
  src/components/ListPage/FilterSort/FilterSort.jsx
  src/components/ListPage/PlanCard/PlanCard.jsx
  src/components/ListPage/PlanCardSystem/PlanCardSystem.jsx
  src/components/ListPage/PlanGrid/PlanGrid.jsx
  src/components/ListPage/TabMenu/TabMenu.jsx
  src/components/MyPage/UserBenefits.jsx
  src/components/MyPage/UserPlan.jsx
  src/components/PlanCompare/AiCompareSummary.jsx
  src/components/PlanCompare/PlanComparePage.jsx
  src/components/PlanCompare/PlanComparePageMobile.jsx
  src/components/ScrollToTopButton.jsx
  src/components/chatbot/MessageInput.module.css
  src/components/chatbot/MessageItem.module.css
  src/components/chatbot/SimpleMode.jsx
  src/components/chatbot/SimpleModeForm.jsx
  src/hooks/useChat.js
  src/hooks/useSocket.js
  src/pages/MainPage.jsx
  src/pages/MainPage.module.css
  src/pages/MyPage.jsx
  src/pages/PlanListPage.jsx
  src/pages/section/BenefitsSection.jsx
  src/pages/section/HeroSection.jsx
  src/pages/section/SolutionSection.jsx
  src/pages/section/TextAnimation.jsx
  src/pages/section/UserProblems.jsx
Labels: REFACTOR

#63 Fix: 백그라운드 스크롤 되던 현상 수정
  src/components/ListPage/FilterModal/FilterModal.jsx
Labels: BUG, REFACTOR

#64 Fix: 푸터 반응형 수정
  src/components/Footer.jsx
Labels: BUG

#65 Fix: 전체 피드백 반영
  index.html
  public/og-image.jpg
  src/components/Header.jsx
  src/components/MyPage/UserNoPlan.jsx
  src/components/MyPage/UserPlan.jsx
  src/components/PlanCompare/AiCompareSummary.jsx
  src/components/PlanCompare/PlanComparePageMobile.jsx
  src/pages/KakaoExtraInfoPage.jsx
  src/pages/LoginPage.jsx
  src/pages/PlanListPage.jsx
Labels: REFACTOR, STYLE, FEAT

#67 Fix: 피드백 반영
  index.html
  src/components/PlanCompare/AiCompareSummary.jsx
  src/components/PlanCompare/PlanComparePage.jsx
  src/components/PlanCompare/PlanComparePageMobile.jsx
  src/index.css
  src/pages/section/HeroSection.jsx
Labels: CHORE, STYLE

#70 Fix: 챗봇 전송버튼 및 faq 수정
  src/assets/sendarrow.svg
  src/components/chatbot/ChatContainer.jsx
  src/components/chatbot/ChatMode.jsx
  src/components/chatbot/MessageInput.jsx
  src/components/chatbot/MessageInput.module.css
Labels: REFACTOR, STYLE

#69 Fix: 요금제 혜택 UI 조건 수정
  src/components/MyPage/UserBenefits.jsx
Labels: BUG, REFACTOR
